#ifndef _HEADER_GUARD_OGLE_MATERIAL_H_
#define _HEADER_GUARD_OGLE_MATERIAL_H_

#include "libogle/o_common.h"
#include "libogle/o_vector3.h"

enum OGLE_MATERIAL_ID
{
	OGLE_MATERIAL_EMERALD,
	OGLE_MATERIAL_JADE,
	OGLE_MATERIAL_OBSIDIAN,
	OGLE_MATERIAL_QUARTZ,
	OGLE_MATERIAL_PEARL,
	OGLE_MATERIAL_RUBY,
	OGLE_MATERIAL_TURQUOISE,
	OGLE_MATERIAL_BRASS,
	OGLE_MATERIAL_BRONZE,
	OGLE_MATERIAL_CHROME,
	OGLE_MATERIAL_COPPER,
	OGLE_MATERIAL_GOLD,
	OGLE_MATERIAL_SILVER,
	OGLE_MATERIAL_BLACK_PLASTIC,
	OGLE_MATERIAL_CYAN_PLASTIC,
	OGLE_MATERIAL_GREEN_PLASTIC,
	OGLE_MATERIAL_RED_PLASTIC,
	OGLE_MATERIAL_WHITE_PLASTIC,
	OGLE_MATERIAL_YELLOW_PLASTIC,
	OGLE_MATERIAL_BLACK_RUBBER,
	OGLE_MATERIAL_CYAN_RUBBER,
	OGLE_MATERIAL_GREEN_RUBBER,
	OGLE_MATERIAL_RED_RUBBER,
	OGLE_MATERIAL_WHITE_RUBBER,
	OGLE_MATERIAL_YELLOW_RUBBER,
	OGLE_MATERIAL_COUNT
};

typedef struct o_material_tag_t
{
	o_vector3_t m_ambient;
	o_vector3_t m_diffuse;
	o_vector3_t m_specular;
	float m_shininess;
} o_material_t;

const o_material_t* ogle_material_get(int32_t material_id);
void ogle_material_set_shader(const char* var_name, const o_material_t* material);

#endif // _HEADER_GUARD_OGLE_MATERIAL_H_
